---
title: "HRRR download"
author: "Megan Sears"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(aws.s3)
library(furrr)
library(terra)
library(tictoc)

```

# Inputs for HRRR download

```{r}

# Timeframe to download
startDate <- ymd('2023-06-02')
endDate <- ymd('2023-06-02')
hours <- sprintf("%02d", 0:23)

# Location to save grib2
localFolder <- "/Users/megansears/Documents/ARS/HRRR/test"

# Number of cores to use for download
cores <- 8

```

# Pull HRRR from S3 bucket

```{r}

tic()

# Download function
downloadHRRR <- function(date, hour) {
  
  # Path to s3 file
  file_key <- paste0(
    "hrrr.", format(date, "%Y%m%d"), "/conus/",
    sprintf("hrrr.t%sz.wrfsfcf00.grib2", hour)
  )
  
  # Save to local with date
  local_file <- file.path(
    localFolder,
    paste0("hrrr_", format(date, "%Y%m%d"), "_", hour, "z.grib2")
  )
  
  if (!file.exists(local_file)) {
    tryCatch({
      
      Sys.sleep(1) # added this so it pauses b/c parallel processing
      
      # Export with message
      save_object(
        object = file_key,
        bucket = "noaa-hrrr-bdp-pds",
        file = local_file,
        anonymous = TRUE
      )
      message("Downloaded: ", file_key)
    }, error = function(e) {
      message("Failed: ", file_key, " | Reason: ", e$message)
    })
  } else {
    message("Skipped (exists): ", file_key)
  }
}

# Set up parallel processing
plan(multisession, 
     workers = cores)

dates <- seq(startDate, 
             endDate, 
             by = 'day')

# Dataframe of dates
timeseries <- expand.grid(
  date = dates,
  hour = hours,
  stringsAsFactors = FALSE) %>% 
  arrange(date)

# Run the function
future_walk(
  seq_len(nrow(timeseries)),
  function(i) {
    row <- timeseries[i, ]
    downloadHRRR(row$date, row$hour)
    }
)

# Turn off paralell processing
plan(sequential)

toc()

```

# Extract sites from grib2 files

```{r}

# List files 
files <- list.files(
  "/Volumes/Sears_ARS/HRRR23",
  pattern = "\\.grib2$",
  full.names = T)

length(files)

# Read csv w/ coordinates
sites <- read_csv("/Users/megansears/Documents/ARS/HRRR/AmeriFlux_Sites_SKP.csv")

# Convert to spatvector
sitesSpat <- vect(
  sites,
  geom = c("lon","lat"),
  crs = "EPSG:4326")

# Use an example grib2 to set up cell index and get projection
rastTemplate <- rast(files[1])

# Project sites to HRRR CRS
sitesProj <- project(sitesSpat, 
                      crs(rastTemplate))

# Get coords from siteProj
xy <- crds(sitesProj)

# Get raster cell index that correspond to site coords
cells <- cellFromXY(rastTemplate, 
                    xy)

# Get datetime from file names
datetimes <- as.POSIXct(
  str_extract(basename(files), "[0-9]{8}_[0-9]{2}") |> 
    str_replace("_",""),
  format = "%Y%m%d%H",
  tz = "UTC" # HRRR in UTC
)

# Extract cells function from all grib2 files
extractCells <- function(file, 
                         dt, 
                         cells, 
                         siteID){

  tryCatch({
  r <- rast(file)

  # Extract values via direct indexing
  vals <- values(r)[cells, ]

  df <- as.data.frame(vals)

  df$siteID <- siteID
  df$datetime <- dt

  df
}, error = function(e) {
    message("Error with file: ", file)
    return(NULL)
  })
}


# Run the function
tic("Extract HRRR sites")

plan(multisession, 
     workers = 4)

final_df <- future_map2_dfr(
  files,
  datetimes,
  extractCells,
  cells = cells,
  siteID = sites$siteID
)

toc()

# Go back to sequential
plan(sequential)

final_df <- final_df %>%
  relocate(datetime) %>%
  relocate(siteID,
           .after=datetime)

# Save dataframe
write.csv(final_df,
          "/Users/megansears/Documents/ARS/HRRR/summer2023.csv")

```

# Testing

Checking random timesteps 

```{r}

# Read csv w/ coordinates
sites <- read_csv("/Users/megansears/Documents/ARS/HRRR/AmeriFlux_Sites_SKP.csv")

# Convert to spatvector
sitesSpat <- vect(
  sites,
  geom = c("lon","lat"),
  crs = "EPSG:4326")

# pull in a random raster
test21 <- rast('/Users/megansears/Documents/ARS/HRRR/test/hrrr_20230602_04z.grib2')

sitesProj <- project(sitesSpat, 
                      crs(test21))


extract <- terra::extract(test21, sitesProj)

extract

```

